import Head from 'next/head'
import React from 'react'

const Cancel = () => {
  return (
    <>
    <Head>
    <title>Cancel | {process.env.NEXT_PUBLIC_SITE_NAME}</title>
    <meta name="description" content="Generated by Mamshouse " />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
  </Head>
    <div className='mt-20'>Cancel</div>
    </>
  )
}

export default Cancel