import Link from 'next/link';
import React from 'react';
import { ContactUsBannerBg } from '../public';
import { Footer, PageBanner } from '../src/components';
import { FiMenu } from 'react-icons/fi';
import { HiOutlineArrowSmRight } from 'react-icons/hi';
import { GrHomeRounded } from 'react-icons/gr';
import { IoLogoInstagram } from 'react-icons/io';
import { BsEnvelope, BsTelephone } from 'react-icons/bs';
import Head from 'next/head';

export default function Contact() {
  return (
    <div>
      <Head>
        <title>Contact Us | {process.env.NEXT_PUBLIC_SITE_NAME}</title>
        <meta name="description" content="Generated by Mamshouse " />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <PageBanner
        src={ContactUsBannerBg}
        heading="Contact"
        pageType="contact"
        info="If you have any questions or comments about the Mamshouse project, please feel free to reach out to us through our contact page. "
      />
      <section className="container mx-auto mt-28 p-2 md:p-0">
        <div className="md:flex items-center">
          <div className="md:8/12 lg:w-9/12">
            <div className="max-w-[500px]">
              <h3 className="font-bangla-mn text-[38px]">Nous contacter</h3>
              <p className="mt-2 font-light text-base">
                We would love to hear from you and are happy to provide any
                information or assistance you may need. Thank you for your
                interest in supporting our mission!
              </p>
            </div>
          </div>
          <div className="md:w-4/12 lg:w-3/12 mt-8 md:mt-0">
            {/* socials */}
            <ul className="w-full flex p-0 md:pl-10 flex-col justify-center gap-6">
              <li>
                <Link
                  href="https://www.instagram.com/mamshouse"
                  target="__blank"
                  className="flex items-center gap-3"
                >
                  <IoLogoInstagram size={22} />
                  <span className="font-light text-base">@mamshouse</span>
                </Link>
              </li>
              <li>
                <Link
                  href="mailto:hello@mamshouse.com"
                  target="__blank"
                  className="flex items-center gap-3"
                >
                  <BsEnvelope size={18} />
                  <span className="font-light text-base">
                    hello@mamshouse.com
                  </span>
                </Link>
              </li>
              <li>
                <Link
                  href="tel:+221 123 456"
                  target="__blank"
                  className="flex items-center gap-3"
                >
                  <BsTelephone size={17} />
                  <span className="font-light text-base">+221 123 456</span>
                </Link>
              </li>
            </ul>
          </div>
        </div>
        {/* 2 */}
        <div className="md:flex mt-20 items-center">
          <div className="md:w-8/12 lg:w-9/12">
            <div className="max-w-[500px]">
              <h3 className="font-bangla-mn text-[38px]">Reservation</h3>
              <p className="mt-2 font-light text-base">
                Mamshouse is a selection of incredible places in the rural
                landscape of Senegal
              </p>
            </div>
          </div>
          <div className="md:4/12 lg:w-3/12 mt-8 md:mt-0">
            <button className="main-btn w-full" href="/">
              <Link href="/residences">réserver maintenant</Link>
            </button>
            <button
              href="+221 123 456"
              target="__blank"
              className="mt-6 underline text-center font-semibold text-xs flex items-center gap-1 justify-center w-full"
            >
              réserver sur Whatsapp <HiOutlineArrowSmRight size={18} />
            </button>
          </div>
        </div>
        {/* 3 */}
        <div className="md:flex mt-20 mb-20 md:mb-40 items-center">
          <div className="md:w-8/12 lg:w-9/12">
            <div className="max-w-[500px]">
              <h3 className="font-bangla-mn text-[38px]">Locations</h3>
              <p className="mt-2 font-light text-base">
                Route du Pilier, 22600 Poppengnne, Senegal: This location is in
                the city of Poppengnne in Senegal.
              </p>
            </div>
          </div>
          <div className="md:w-4/12 lg:w-3/12 mt-8 md:mt-0">
            <button className="text-sm gap-2 underline lg:whitespace-nowrap flex justify-center items-center">
              <GrHomeRounded size={14} />
              1 route du pilier, 22600 Poppengine, Sénégal
              <HiOutlineArrowSmRight size={16} />
            </button>
            <button className="text-sm mt-3 underline gap-2 lg:whitespace-nowrap flex justify-center items-center">
              <GrHomeRounded size={14} />
              1 route du pilier, 22600 Poppengine, Sénégal
              <HiOutlineArrowSmRight size={16} />
            </button>
          </div>
        </div>
      </section>
      <Footer />
    </div>
  );
}
