import Head from 'next/head';
// import { Inter } from "@next/font/google";
import { sanityClient } from '../src/config/sanityClient';
import { Filter, HomeCard, Main } from '../src/components';
import { useRouter } from 'next/router';

// const inter = Inter({ subsets: ["latin"] });
export default function Home({ activities, residences }) {
  const router = useRouter()
  const { arrival, depart, location, origin, travelers} = router.query
  console.log("🚀 ~ residences", residences)


  return (
    <>
      <Head>
        <title>Mamshouse </title>
        <meta name="description" content="Generated by Mamshouse " />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <script src="https://js.stripe.com/v3/"></script>
      </Head>
      <Main />
      <section className="md:-mt-32 -mt-12 p-1" >
        <Filter />
      </section>
      <section className="md:mt-12 mt-6 mb-20" id="homecard">
     
        <HomeCard />
      </section>
      
    </>
  );
}




export async function getServerSideProps(pageContext) {
  const locale = pageContext.query.lang || 'en';
  const residences = await sanityClient.fetch(
    `*[_type == "residences"]{
        _id,
        "title": title[$locale],
        "location": location[$locale], 
        slug,
        feature_poster{
          asset->{
            url
          }
        },
        feature_banner{
          asset->{
            url
          }
        },
        "short_info" : short_info[$locale],
        gallery[]{
          asset->{
            url
          }
        },
        price_per_unit,
        "description" : description[$locale],
        features[]{
          title,
          icon{
            asset->{
              url
            }
          }
        }


  }`,
    { locale }
  );

  return {
    props: {
      residences,
    },
  };
}
