import axios from "axios";
import Head from "next/head";
import { useRouter } from "next/router";
import React, { useEffect, useState } from "react";


const Success = ({ res }) => {
  const router = useRouter();

  

  return (
    <>
      <Head>
        <title>Success | {process.env.NEXT_PUBLIC_SITE_NAME}</title>
        <meta name="description" content="Generated by Mamshouse " />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div className="mt-20 h-[80vh] body flex justify-center flex-col items-center text-center">
        <div className="card flex flex-col justify-center items-center">
          <div className="bg-green-100 w-[200px] mx-auto rounded-full flex justify-center items-center flex-col">
            <i className="checkmark ">✓</i>
          </div>
          <h1>Success</h1>
          <p>
            We received your purchase request;
            <br /> we'll be in touch shortly!
          </p>
        </div>
      </div>
    </>
  );
};

export default Success;




export async function getServerSideProps(pageContext) {
  const {title,getStartDate,getEndDate,totalprice,paymentApproved} = pageContext.query

  await axios
    .post(`${process.env.NEXT_PUBLIC_SITE_URL}/api/createOrder`, {
      title,
      getStartDate,
      getEndDate,
      totalprice,
      paymentApproved
    })
    .then(function (response) {
      
      
    })
    .catch(function (error) {
      console.log(error);
    });
  
    
    
  const Emptyres = [];
  return {
    props: {
      Emptyres,
    },
  };
}
