import axios from 'axios';
import Head from 'next/head';
import Link from 'next/link';
import { useRouter } from 'next/router';
import React, { useEffect, useState } from 'react';
const stripe = require('stripe')(
  'sk_test_51KZccKBYpJVF6ADtJIF54auA6RHJEEiEBasxyMMN8hvwOC2czH4rSBdt0tRCwCMw9gYUxynchdG5yjxCjYp44JyF00tvx0T4gJ'
);

const Success = ({ res, session }) => {
  return (
    <>
      <Head>
        <title>Success | {process.env.NEXT_PUBLIC_SITE_NAME}</title>
        <meta name="description" content="Generated by Mamshouse " />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div className="mt-20 h-[80vh] body flex justify-center flex-col items-center text-center">
        <div className="card flex flex-col justify-center items-center">
          <div className="bg-green-100 w-[200px] mx-auto rounded-full flex justify-center items-center flex-col">
            <i className="checkmark ">✓</i>
          </div>
          <h1>Success</h1>
          <p>
            We received your purchase request;
            <br /> we'll be in touch shortly!
          </p>
          <div className="mt-6">
            <Link
              href="/"
              className="uppercase bg-black text-white px-8 text-sm py-3"
            >
              Back to Home
            </Link>
          </div>
        </div>
      </div>
    </>
  );
};

export default Success;

export const getServerSideProps = async (context) => {
  const id = context.query.session_id;
  const title = context.query.title;
  const getStartDate = context.query.getStartDate;
  const getEndDate = context.query.getEndDate;
  const totalprice = context.query.totalprice;
  const paymentApproved = context.query.paymentApproved;

  const session = await stripe.checkout.sessions?.retrieve(id);
  const email = session.customer_details?.email;

  if (session.status === 'complete') {
    await axios
      .post(`https://mamshouse.com/api/createOrder`, {
        title,
        getStartDate,
        getEndDate,
        totalprice,
        paymentApproved: true,
        email,
      })
      .then(function (response) {
        console.log('Order Submited');
      })
      .catch(function (error) {
        console.log(error);
      });
  }
  if (session.status === 'complete') {
    fetch(`https://mamshouse.com/api/sendMail`, {
      method: 'POST',
      headers: {
        Accept: 'application/json, text/plain, */*',
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        title,
        getStartDate,
        getEndDate,
        totalprice,
        paymentApproved: true,
        email,
      }),
    }).then((res) => {
      // console.log('Response received')
      if (res.status === 200) {
        console.log('Response succeeded!');
      }
    });
  }

  return {
    props: {
      session,
    },
  };
};
