import axios from 'axios';
import Head from 'next/head';
import { useRouter } from 'next/router';
import React, { useEffect } from 'react'

const Success = () => {

  return (
    <>
    <Head>
    <title>Success | {process.env.NEXT_PUBLIC_SITE_NAME}</title>
    <meta name="description" content="Generated by Mamshouse " />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
  </Head>
    <div className='mt-20'>Success</div>
    </>
  )
}

export default Success